apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- marketplace-be-api-deployment.yaml
- marketplace-be-api-namespace.yaml
- marketplace-be-api-service.yaml
namespace: backend
images: