---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api-nodeport-svc
  namespace: backend
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 32121
  selector:
    app: api
  type: NodePort