apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: marketplace-be-api
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api
    spec:
      containers:
      - image: image
        name: api