apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api-nodeport-svc
  namespace: backend
spec:
  ports:
  - nodePort: 32121
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: marketplace-be-api
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api
    spec:
      containers:
      - image: 192.168.110.135:5000/api:915a8aa8
        name: api
        resources:
          limits:
            cpu: 256m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 32Mi
